<template>
  <div class="container">
    <h1>Hello!</h1>
    <section>
      <article>
        <h1>Title</h1>
      </article>
      <article>
        <h1>Title</h1>
      </article>
      <article>
        <h1>Title</h1>
      </article>
      <article>
        <h1>Title</h1>
      </article>
    </section>
  </div>
</template>
